library(tidyverse)

source("clean.R")
source("functions.R")

df <- read.csv("./data/credit_score.csv")
# df_strasfact <- read.csv("./data/credit_score.csv", stringsAsFactors = TRUE)

names(df) <- tolower(names(df))
df <- clean_df_chars(df)
df <- convert_chrtoint(df)
df <- convert_chrtodbl(df)
df <- clean_occupation(df)
df <- clean_num_bank_accounts(df)
df <- clean_num_credit_cards(df)
df <- clean_interest_rate(df)
df <- clean_delay_from_due_date(df)
df <- clean_num_of_delayed_payment(df)
df <- clean_num_credit_inquiries(df)
df <- clean_total_emi_per_month(df)
df <- clean_amount_invested_monthly(df)
df <- clean_changed_credit_limit(df)
df <- clean_num_of_loan(df)
df <- clean_montly_inhand_salary(df)
df <- convert_strtofact(df)

max       (df$delay_from_due_date, na.rm = TRUE)
min       (df$delay_from_due_date, na.rm = TRUE)
mean      (df$delay_from_due_date, na.rm = TRUE)
median    (df$delay_from_due_date, na.rm = TRUE)
get_mode  (df$delay_from_due_date)
sum(is.na (df$delay_from_due_date))
summary   (df$delay_from_due_date)
table     (df$delay_from_due_date)
unique    (df$delay_from_due_date)
hist      (df$delay_from_due_date)
class     (df$delay_from_due_date)

View(df)

write.csv(df, "./data/clean_credit_score.csv", row.names=FALSE)
